### ISSUE TITLE
Description should mention that this extension adds sprites to the image gallery

### ISSUE THREAD

**Issue by riknoll** [adafruit/Circuit-Playground-Character-Icons#4]
We've gotten feedback that people are confused when adding this package because it doesn't add any blocks:

https://github.com/microsoft/pxt-arcade/issues/1360

It would help if the repo description made that clear. I think we just grab it from the Github description. The current text is "some cute icons!"

**Comment by ladyada** [comment]
changed

**Comment by riknoll** [comment]
Thanks!
